### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by AaronDavidSchneider** [bordaigorl/remy#2]
As you requested feedback, I will try to give some using a new issue. Remy it self works flawlessly! Thanks!

Some issues I faced:
1. Before I was able to start, I needed to manually copy the template folder from my remarkable to my remy folder
2. Segmentation faults and errors, when opening up PDFs (probably only due to my anaconda setup)
```
sent 76 bytes  received 36539 bytes  24410.00 bytes/sec
total size is 532032  speedup is 14.53
LOAD TIME: 1.031118
objc[70088]: Class RunLoopModeTracker is implemented in both /Users/schneider/anaconda3/lib/libQt5Core.5.dylib (0x10a640a80) and /usr/local/opt/qt/lib/QtCore.framework/Versions/5/QtCore (0x126a7cb40). One of the two will be used. Which one is undefined.
```
3. erasing strokes are also acknowledged. I think its possible to remove those (@ddvk had a method to do that), Only effects the preview, not the export.
<img width="544" alt="Screenshot 2020-07-07 at 13 42 12" src="https://user-images.githubusercontent.com/7556347/86776287-60afa400-c058-11ea-80e5-e9dd7bd9731f.png">

4. Where to put `remy-banner.png`? I used `/usr/share/remarkable` and it didnt recognise it.

5. It would be extremly nice to be able to export multiple files (like a folder) to pdf and save them on the computer :D

Thanks again!

**Comment by bordaigorl** [comment]
Hi thanks for the feedback!

> 1. Before I was able to start, I needed to manually copy the template folder from my remarkable to my remy folder

Yes, that is needed with the "local" source type.

> 2. Segmentation faults and errors, when opening up PDFs (probably only due to my anaconda setup)

Things like crashes are best reported as separate issues with some info to reproduce.
I did have to work around installation issues myself to get python-poppler-qt5 to work on my system, so that may explain the issues with PDFs.

> 3. erasing strokes are also acknowledged. I think its possible to remove those (@ddvk had a method to do that), Only effects the preview, not the export.

They should only be there in the preview mode (because they are faster to render) but should not be visible in exported pdfs. If you prefer to have them properly rendered in the preview as well you can change line 401 in `notebookview.py` to

    self._page_cache[i] = self.makePageScene(i, fancyEraser=True)

This will be controlled via settings soon.

> 4. Where to put `remy-banner.png`? I used `/usr/share/remarkable` and it didnt recognise it.

You can put it in your home on the tablet, but you can also write the full absolute path in the `use_banner` setting.

> 5. It would be extremly nice to be able to export multiple files (like a folder) to pdf and save them on the computer :D

I agree 😉 it's in the roadmap.

**Comment by AaronDavidSchneider** [comment]
Awesome! That sounds good! Thanks for the tool!

**Comment by bordaigorl** [comment]
@jagorostiza did you manage to solve your problem? I added new instructions in the Readme concerning poppler-qt5.
If you still face problems open a new issue. I can also provide a standalone bundle (was planning to do so for a more mature version of the app)
