### ISSUE TITLE
Slow loading

### ISSUE THREAD

**Issue by pityhero233** [bordaigorl/remy#31]
Hi all,

Not sure if this behaviour is experienced by others, but everytime I run remy, it takes 1-2 minutes to run the initialization ...

**Comment by bordaigorl** [comment]
1-2 minutes is definitely longer than usual.
It takes a few seconds for me.
Connection speed and the amount of documents might influence this but over a minute seems excessive.
Are you running remy from a bundle or from sources? Which OS? Which connection method? What do you see while it loads?

**Comment by bordaigorl** [comment]
> I am running from SSH source.

this might be the problem: try using the rsynch source, it is way more efficient. Recent versions of the RM firmware should have rsync by default and not require any additional step for you to use it.

> Is remy downloading every pdf file each time it boot up though, or is it just downloading thumbnail and metadata?

Just metadata, not even thumbnail. The thing is though, the SSH method is inefficient and does not download "just the diffs" but the whole thing. I included it more because it could support rsync-less versions of RM than anything else. The default and recommended method should be rsync.

> Also I noticed after an update now my rM xochitl interface freezes everytime I use reMy to connect to it ... Maybe I should open a new issue for that though

That is expected (and desired) behaviour if you have the [`use_banner`](https://github.com/bordaigorl/remy#the-use_banner-option) option activated.
The idea is that you should not use `xochitl` while using remy as there could be concurrent updates to the same files and that could lead to conflicts; plus, to get `xochitl` to pick up on the updates, you need to restart it anyway.
If you follow the instruction linked above you can display a banner while using remy instead of just seeing the frozen UI.
If you know what you are doing you can disable the `use_banner` option, taking care of not using `xochitl`  while using remy, and that way you avoid a restart when all you did with remy was downloading stuff (uploading still requires a restart).

**Comment by pityhero233** [comment]
Thank you! Setting Rsync totally resolved issue, and the 'freeze' is indeed as you explained.
