### ISSUE TITLE
All notebooks are blank

### ISSUE THREAD

**Issue by xade93** [bordaigorl/remy#59]
Hi,

I have been using ReMy since last year, but haven't touched it for quite a while xD. Just picked up my dusty Remarkable, and I noticed that all my notebooks render as blank in Remy. Other PDF books seems to be ok.

![image](https://github.com/bordaigorl/remy/assets/24752033/5b724caa-d911-4765-86c9-d2a99096df23)

After I download those files with builtin downloader and open with system PDF readers, they show up as empty as well.

**Comment by bordaigorl** [comment]
Hi, when you just view documents from the tablet, Remy does not modify anything at all on the tablet itself.
Therefore your notebooks have been somehow corrupted by the tablet's software before they reached Remy.
In addition, the fact that the official app is also showing them as blank means that Remy is displaying them according to specification.

As to the actual cause of the problem (which seems to have nothing to do with Remy) I can only speculate.
You are saying you haven't been using the tablet for a long while before picking it up again.
In such cases there are a couple of things that can be problematic:

1. the sync mechanism of the tablet might have lost compatibility with the new sync that is supported by the server (the sync has been reported as misbehaving and corrupt/delete files in some corner cases)
2. the firmware might have been updated by the tablet from an old to a very new version in one go (maybe skipping intermediate versions). Since the format of the documents has changed between certain versions, it is possible that the conversion from the old to the new went wrong, giving you blank files.

What would maybe help diagnose the situation is knowing the version of the firmware, the settings for sync, and the contents of the `/home/root/.local/share/remarkable/xochitl` folder on your tablet. In particular, pick a document you know should have contents but is displayed as blank, note down its ID. Then track down the folder with that ID in `/home/root/.local/share/remarkable/xochitl` and see if it contains any `rm` files. If so, and the files are not empty, there might be a chance of recovering the contents.
If you made a backup of the files at any point in time, it is also possible to use Remy to browse the backup directly.
In any case you might want to contact the Remarkable support.
